# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantID', models.IntegerField()),
                ('soil_misture', models.FloatField(default=370)),
                ('pH', models.FloatField(default=7)),
                ('temperature', models.FloatField(default=25)),
                ('rainfall_Chances', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankID', models.IntegerField()),
                ('tankWaterLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tank_linked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Tank'),
        ),
    ]
