# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='rainfall_Chances',
            new_name='rainChances',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='soil_misture',
            new_name='soilMoisture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tank_linked',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='time',
        ),
        migrations.AddField(
            model_name='plant',
            name='tankWaterLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
