# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_plant_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
                ('height', models.FloatField()),
                ('tankWaterLevel', models.FloatField(default=0)),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='rainChances',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tankWaterLevel',
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity',
            field=models.FloatField(default=40),
        ),
    ]
