# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_auto_20170921_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertank',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
