# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20170921_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertank',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
