# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_watertank_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertank',
            name='rain',
            field=models.BooleanField(default=False),
        ),
    ]
