# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_watertank_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertank',
            name='rain',
            field=models.BooleanField(),
        ),
    ]
